server:
  port: 8080

spring:
  application:
    name: tp-api-gateway

spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://identity-service:8080/
          predicates:
            - Path=/api/v1/auth/**
        - id: opportunity-route
          uri: http://tp-opportunity-service:8081/
          predicates:
            - Path=/api/v1/opportunities/**

jwt:
  secret: change-me-please-256-bit-secret-change-me-please

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
